// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWazDLdZ7EkxkW33Ox3SQFTidxR7unNqY',
    appId: '1:505191385572:web:65f3c7c983397e5d1c5ff1',
    messagingSenderId: '505191385572',
    projectId: 'flutbo',
    authDomain: 'flutbo.firebaseapp.com',
    storageBucket: 'flutbo.appspot.com',
    measurementId: 'G-9HP2E85FCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRx63kVo1p5xigsqurmeUXxSeHGp6D90A',
    appId: '1:505191385572:android:0e677c6fffd96b5d1c5ff1',
    messagingSenderId: '505191385572',
    projectId: 'flutbo',
    storageBucket: 'flutbo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7F5s-apIUEqwomHGZ6pYDnwsjl4BqbEY',
    appId: '1:505191385572:ios:afdec8b80bf4e62f1c5ff1',
    messagingSenderId: '505191385572',
    projectId: 'flutbo',
    storageBucket: 'flutbo.appspot.com',
    iosBundleId: 'com.example.blogging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7F5s-apIUEqwomHGZ6pYDnwsjl4BqbEY',
    appId: '1:505191385572:ios:d18b8de39a92bea91c5ff1',
    messagingSenderId: '505191385572',
    projectId: 'flutbo',
    storageBucket: 'flutbo.appspot.com',
    iosBundleId: 'com.example.blogging.RunnerTests',
  );
}
